version=2.7.21

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8

assertjVersion=3.27.3
commonsCodecVersion=1.18.0
hamcrestVersion=2.2
jacksonVersion=2.14.3
junitJupiterVersion=5.8.2
kotlinVersion=1.6.21
mavenVersion=3.9.4
springFrameworkVersion=5.3.41
tomcatVersion=9.0.102

kotlin.stdlib.default.dependency=false
