subprojects {
	apply plugin: 'signing'
	/**
	 * signing.properties 文件内容示例如下
	 * signing.keyId=xx
	 * signing.password=xxx
	 * signing.secretKeyRingFile=C:/Users/admin/.gnupg/**_SECRET.gpg
	 *
	 * ossrhUsername=xx
	 * ossrhPassword=xxx
	 */
	File signing_cfg = new File("$project.rootDir/signing.properties")
	if(signing_cfg.exists()) {
		Properties props = new Properties()
		props.load(new FileInputStream(signing_cfg))
		props.each { prop ->
			project.ext.set(prop.key, prop.value)
		}

	}

	project.plugins.withType(MavenPublishPlugin.class).all {
		PublishingExtension publishing = project.getExtensions().getByType(PublishingExtension.class);
		if (project.hasProperty("releasesRepository")) {
			publishing.repositories.maven {
				if(version.endsWith('SNAPSHOT')){
					it.url = project.property("snapshotsRepository")
				}else{
					it.url = project.property("releasesRepository")
				}
				it.name = "deployment"
				it.credentials {
					it.username = project.property("ossrhUsername")
					it.password = project.property("ossrhPassword")
				}
			}
		}
	}

	afterEvaluate {
		if (plugins.hasPlugin('org.springframework.boot.deployed') ) {
			// 将构建的包签名
			signing {
				sign publishing.publications.maven
			}
		}
	}
}
